### ISSUE TITLE
Problems with query processing that didn't create a View

### ISSUE THREAD

**Issue by CalendulaED** [onlyzdd/clinical-fusion#4]
After setup the database with postgresql, I have tried to run the SQL in the `query` folder.

For example, this is what happen when I run the adm_details.sql: It shows `SELECT 0`
![image](https://user-images.githubusercontent.com/68514251/120975790-36a0bd80-c7a4-11eb-8edd-cb9153792947.png)

So I think it doesn't generate any views, not sure how to solve this. This also happens when I run other SQL
Thank you

**Comment by onlyzdd** [comment]
Sorry to hear that it's not working on your computer, @CalendulaED. These queries works well on my computer. I'm not very sure whether the problem is caused by your MIMIC-III database setup. Could you please check whether you have imported the `*.csv` data files to your local Postgres database correctly? (Try `SELECT count(*) FROM patients` for example) If not, please follow https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iii/buildmimic/postgres.

<img width="463" alt="D71156C3-3999-47B9-8CE0-7C0DA472903A" src="https://user-images.githubusercontent.com/13433549/120982679-86cf4e00-c7ab-11eb-942d-5b6d5431ad27.png">

**Comment by CalendulaED** [comment]
Thank you so much for your help!
I have tried to `SELECT count(*) FROM patients` and it output nothing. So maybe the problem is from the Postgres database.
![image](https://user-images.githubusercontent.com/68514251/120985011-c6973500-c7ad-11eb-9ed1-c2bdc5fa672d.png)

However, I did follow each procedure to build the database....
May I ask which version of the Postgres are you currently use? I am currently using Postgres 10.

Thank you so much for your help!

**Comment by onlyzdd** [comment]
Sorry to hear this. Currently, I'm using Postgres 9.4.24.
Please follow https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iii/buildmimic/postgres, I think it should work well with newer Postgres versions. Please let me know if you have any other problems.

**Comment by CalendulaED** [comment]
I have managed to solve the problem by specifying the schema.

Thank you so much for your help!
